### ISSUE TITLE
Connecting to multiaddrs with peerids

### ISSUE THREAD

**Issue by koivunej** [rs-ipfs/rust-ipfs#105]
After #104 there are multiaddr cases which either do not return an error or hang the http request at least:

1. `GET /swarm/connect?arg=/ip4/127.0.0.1/tcp/4001/ipfs/peerid` is invalid query string (as expected)
2. `GET /swarm/connect?arg=/ip4/127.0.0.1/tcp/4001/p2p/peerid` hangs, doesn't connect according to logging
3. `GET /swarm/connect?arg=/ip4/127.0.0.1/tcp/4001/p2p/typoed_peerid` hangs, doesn't connect according to logging

Where `/ip4/127.0.0.1/tcp/4001` is a local `go-ipfs-0.4.23` and `peerid` is it's peer id, `typoed_peerid` the same but with with single different character.

I didn't investigate these further nor is it clear we need this functionality for the conformance tests. 

Could be that this work can be factored out to parts:

1. if rust-libp2p already gives an error for addresses with p2p in them we are hanging instead of catching that case, which we should be doing either way (the second test case above)
2. dialing an expected peerid with peerid separated from the multiaddr
3. backwards compatible peerid extraction from `/ipfs/peerid` at the `ipfs-http` level

I've understood that rust-libp2p implements dialing to a expected peerid by getting a `NetworkBehaviourAction::DialPeer { peer_id }` followed by offering of addresses for this peerid at `NetworkBehaviour::addresses_of_peer`.

Related discussion over at rust-libp2p: https://github.com/libp2p/rust-libp2p/issues/1462

As the `/ipfs/peerid` seems to be deprecated in favor of `/p2p/peerid` per [comment](https://github.com/libp2p/rust-libp2p/issues/471#issuecomment-420712108) it'd make sense to handle this deprecation (`s!/ipfs/!/p2p/!` style handling) only at `ipfs-http` to get a parsing multiaddr and then move on separating the peerid at some point before asking the Swarm to dial that peerid. There will be some complications and/or duplicate work in `ipfs::p2p::swarm::SwarmApi` related to these two paths. If those cannot be easily dealt with, we could go with requiring the peerid in the multiaddr as ipfs does.

**Comment by koivunej** [comment]
Even with #108 the second case still hangs. This is probably the case of dropped result here: https://github.com/libp2p/rust-libp2p/blob/v0.16.2/swarm/src/lib.rs#L449

**Comment by aphelionz** [comment]
This is 1.2 or later, yes?

**Comment by koivunej** [comment]
Still thinking we should run into this during interop tests when connecting the nodes, but it could happen non problematic way around as well, which would only require #110 .

**Comment by ljedrz** [comment]
No longer hangs; now I only got (for `rust-ipfs` listening at `43799` and `go-ipfs` at `4001` with `PeerId` = `X`):
```
curl -X POST "http://127.0.0.1:43799/api/v0/swarm/connect?arg=/ip4/127.0.0.1/tcp/4001/p2p/X"
{"Message":"Failed(\"Pending connection: Transport error: Multiaddr is not supported: /ip4/127.0.0.1/tcp/4001/p2p/X\")","Code":0,"Type":"error"}
```

**Comment by ljedrz** [comment]
`curl -X POST "http://127.0.0.1:port/api/v0/swarm/connect?arg=MULTIADDR/p2p/PEERID` works now and invalid addresses don't cause hangs; tested against `go-ipfs 0.6`.

**Comment by koivunej** [comment]
It sounds to me that there's no point in the rewriting of `/ipfs/peerid` to `/p2p/peerid` as go-ipfs did the change as well. In hindsight the hangs were about subscription issues which @ljedrz has now fixed... So what remains?

**Comment by ljedrz** [comment]
Nothing :stuck_out_tongue:? I think it's good to close at this point.

**Comment by koivunej** [comment]
Yeah I think nothing remains.
