### ISSUE TITLE
Slow Windows builds

### ISSUE THREAD

**Issue by koivunej** [rs-ipfs/rust-ipfs#114]
The windows builds are currently really slow, mostly because the `vcpkg` which is used for openssl compilation is not cached even thought it probably could be.

- [x] vcpkg caching in #180 
- [x] chocolatey caching

The caching added in #180 will not work if there is a major update to the package. I can't see how to cache using some version key. run-vcpkg action might help in the future, but I don't want to start depending on vcpkg as a submodule.

**Comment by koivunej** [comment]
Reopened after accidential closing via #180, updated the description.

**Comment by aphelionz** [comment]
> The caching added in #180 will not work if there is a major update to the package.

I assume we'll know pretty quickly if this breaks, yeah?

**Comment by koivunej** [comment]
Continued in https://github.com/rs-ipfs/rust-ipfs/pull/195.. Not sure if there's anything more we can do.

**Comment by koivunej** [comment]
The #195 marked the "chocolatey" off the list (updated desc). Closing, as I can't see any other avenues to explore. Most of the time is spent compiling anyways, which is the best we can do.
