### ISSUE TITLE
RFC: Phase 3

### ISSUE THREAD

**Issue by aphelionz** [rs-ipfs/rust-ipfs#181]
Once the IPFS devgrant, and the Substrate grant is complete, we will have the following done:

- HTTP API Scaffolding
    - /pubsub/{ publish, subscribe, unsubscribe, peers, ls }
    - /swarm/{connect, peers, addrs, localAddrs, disconnect }
    - /id
    - /version
    - /shutdown
    - /block/{ get, add, rm, stat }
    - /dag/{ put, resolve }
    - /refs and /refs/local
    - /bitswap/{ stat, wantlist }
    - /cat
    - /get
    - /add
- client or server DHT + swarming support
- UnixFS support

We would love your input for what direction to move toward next. There are some things we're thinking about:

- pinning and different gc strategies
- keygen
- [pubsub fixes](https://github.com/rs-ipfs/rust-ipfs/issues/132)

There are also some acute items from @stebalien already that we haven't forgotten about... but what else? Some time has passed so it bears repeating the question. Also, no guarantees but we'll do our best :crossed_fingers:

**Comment by ribasushi** [comment]
@aphelionz @vmx I don't monitor this repo too closely: hit me up `ribasushi@protocol.ai` when you are ready to do the `add` portion of the work: there's a lot of stuff "ready to translate 1:1", but still a bit in flux.

**Comment by aphelionz** [comment]
Thanks @ribasushi . Tagging @koivunej here as well.

**Comment by aphelionz** [comment]
Thanks everybody! We'll be revisiting this discussion in a future issue.
