### ISSUE TITLE
Examples Review: Phase 2 

### ISSUE THREAD

**Issue by aphelionz** [rs-ipfs/rust-ipfs#196]
I wanted to give the examples a spin, and can report the following findings:

Here are my setup steps:
```bash
$ git clone
$ cargo build --workspace
$ cd examples
$ cargo run --example

Available examples:
    client1
    client2
    fetch_and_cat
    ipfs_bitswap_test
    ipfs_ipns_test
```

- `cargo run --example client1` produces no output to stdout
- `cargo run --example client2` seems to hang indefinitely
- `cargo run --example fetch_and_cat` seems to work, requires a CID. Maybe provide a default? I assume this will improve once we have DHT swarming operational
- `cargo run --example ipfs_bitswap_test` seems to hang indefinitely. 
- `cargo run --example ipfs_ipns_test` panics, can probably be removed?

Overall these could be a lot more user-friendly and showcase the extent of the work that exists inside the crates.

**Comment by koivunej** [comment]
> * cargo run --example fetch_and_cat seems to work, requires a CID. Maybe provide a default? I assume this will improve once we have DHT swarming operational

This was just added and I did include usage, runtime guidance and these comments:

```
    // this example will wait forever attempting to fetch a CID provided at command line. It is
    // expected to be used by connecting another ipfs peer to it and providing the blocks from that
    // peer.
```

Sadly using some default Cid doesn't really seem feasible, unless it was something we'd know would always be available. With client DHT this example would become more useful. Once I get rust-ipfs node running on my rasperrypi, maybe I can semi-consistently provide some previous release tarball :)

The rest of the examples are "legacy," or "early integration test cases." This is all I know of them:

> * cargo run --example client1 produces no output to stdout

This does not seem useful at all.

> * cargo run --example client2 seems to hang indefinitely

I have no idea what this could had done ever, as the path has zero segments. Perhaps different paths were tested manually using this.

> * cargo run --example ipfs_bitswap_test seems to hang indefinitely.

I was about to clean this up while working on the `fetch_and_cat`, but noticed I was already doing a +1k PR.

I remember trying this out as a go-ipfs 0.4.2x testing and the gist is that the first block should be downloadable in the example by connecting a node to it (as long as you can calculate the Cid for it outside the example), and the "block-want" is awaited forever until one is provided. The providing can be done on a throwaway go-ipfs node like `echo -n block-want | ipfs block put`.

**Comment by r-marques** [comment]
The examples seem to be using logging for the output and `env_logger` defaults to only showing error messages unless you specify the logging level with the `RUST_LOG` env variable.

So you can see the output if you run the examples with for example:
```bash
$ RUST_LOG=debug cargo run --example client1
```

Another way would be to change the default log level used by `env_logger` so that you don't have to specify the `RUST_LOG` env variable when running the examples. This can be done by replacing:
```rust
env_logger::init();
```
with
```rust
env_logger::from_env(Env::default().default_filter_or("debug")).init();
```

The log messages should also give you some insight as to why some of the examples are hanging.

**Comment by koivunej** [comment]
@r-marques Good point. I think the examples should be using just println for simplicity sake, maybe diagnostics to eprintln! if stdout is used for something useful, like the file contents with `fetch_and_cat`. 

We may have actually had `RUST_LOG` overwriting code in the past in `ipfs::IpfsOptions`, and could be that the examples expected the automatic env rewriting. It was quite confusing not to have the usual `RUST_LOG` setting getting applied.

**Comment by r-marques** [comment]
I agree that using println would be the way to go for the examples.
