### ISSUE TITLE
ipfs-unixfs: importing

### ISSUE THREAD

**Issue by koivunej** [rs-ipfs/rust-ipfs#214]
Importing or the pre-requisite for `ipfs.add`. Early prototyping suggests this might not be possible to do as `ipfs::Ipfs::add(&self, ???)` but perhaps with an builder kind of API. We'll see how this turns out.

- [x] single-block files (~already~ EDIT: was not done)
- [x] files #215
- [x] ipfs-http streaming multipart handling #224 
- [x] directories #284 
- [x] symlinks #302 
- [x] fix old API, cleanup #306 

Possibly out of scope:

- hamt sharded directories
- other than size chunkers, balanced layout in #222

**Comment by koivunej** [comment]
@ribasushi following up after https://github.com/rs-ipfs/rust-ipfs/pull/176#discussion_r436101657 and after some IPFS core impl weekly where, if I remember correctly, you mentioned you would have some insight you'd want to share when we get to `add`. I don't think you were any more specific about the insights in that call recording. Apologies if I misremember or tagged the wrong person :)

**Comment by ribasushi** [comment]
@koivunej right. I guess easiest would be for us to do a 15 minute audiosync, as a lot of the stuff I was going to point you to is *still* relatively in flux, and not self-descriptive. I am available on `#rust-ipfs`, reach out to me there.

The gist is that I have a lot of the stream-encoding primitives split much better architecturally, compared to how they are wired in `go-ipfs`. Thus using the parts I wanted to walk you through is likely to get you to the end-goal faster.

**Comment by koivunej** [comment]
Got a bit distracted but now back into this looking at tree building for `/add`, once the `/add` starts working hoping to swing back and redo `ipfs::Ipfs::` add related methods, same directly under `ipfs::unixfs::`.

**Comment by koivunej** [comment]
I think this is now ready to be closed. To give another view on the new features we now have:

- [`ipfs_unixfs::file::adder::FileAdder`](https://github.com/rs-ipfs/rust-ipfs/blob/master/unixfs/src/file/adder.rs) for constructing unixfs representations for files
- [`ipfs_unixfs::dir::builder::BufferingTreeBuilder`](https://github.com/rs-ipfs/rust-ipfs/blob/master/unixfs/src/dir/builder/buffered.rs) for constructing unixfs directory trees (only plain old directories)
- [`ipfs_unixfs::symlink::serialize_symlink_block`](https://github.com/rs-ipfs/rust-ipfs/blob/5d5da691dd668f7996fb06d5f200e47a5c1e584e/unixfs/src/symlink.rs) for ... serializing symlinks

All of these come with missing features and bugs such as:

- `FileAdder`: missing trickledag layout
- `FileAdder`: *accidentially quadratic* (or similar) flat leaf storage
  - this could be "optimized" away by looking at `leaves[end - 174]` where end is the `leaves.len()` for lowest level leafs
  - this will probably need to change a lot while looking at how trickledag layout could be implemented
- `FileAdder`: missing different chunkers
- `FileAdder`: new blocks and `Vec<(Cid, Vec<u8>)>` would not need to be created all of the time if iterators similar to [`PostOrderIterator`](https://github.com/rs-ipfs/rust-ipfs/blob/master/unixfs/src/dir/builder/iter.rs) were implemented
- `FileAdder`: reusing across files (look at the [ingest-tar.rs bench](https://github.com/rs-ipfs/rust-ipfs/blob/master/unixfs/benches/ingest-tar.rs))
- `BufferingTreeBuilder`: hamt sharded directories
- everywhere: inline cids

And finally the big thing: `ipfs::Ipfs` APIs! Where are they?

Right now, nowhere. What we do have is "examples" of how to implement the add yourself, given the situation, for example: [add_stream](https://github.com/rs-ipfs/rust-ipfs/blob/master/http/src/v0/root_files/add.rs#L102) on the http side. With "given the situation" I mean that in the http world we have a given situation: `bytes::Bytes` come in from `warp`, they are parsed with `mpart-async` to `bytes::Bytes` which are then [fed to `FileAdder::push`](https://github.com/rs-ipfs/rust-ipfs/blob/04c4e055ab01a3b41eec75bcd0b6bf2c3c1fb984/http/src/v0/root_files/add.rs#L169) and the created blocks are persisted.

How could this work in a more general setting? What would you like to `add` into an Ipfs instance, perhaps a file from a path or a file descriptor? First, how should the file be read -- mmap, std::fs, tokio::fs, does the user have a threadpool for fs operations ready to go or something else? Well, now that #307 has been merged this becomes a bit easier since `bytes::*::BufMut` (or `bytes::BytesMut`) is supported right at `AsyncRead`. Previously I was thinking we cannot really work around the fact that we need `'static`  block data so that it can be sent over channels and *not* use bytes but perhaps we should now adopt the tokio traits, and try to find the more general solutions with [`BufMut`](https://docs.rs/bytes/0.5.6/bytes/trait.BufMut.html).

Apologies for the stream of conciusness writing, I had not understood what the not using tokio had been blocking API design-wise and perhaps we can now move forward more easier. I had been focused more on the fact that we cannot use the more advanced channels and have to write our own boilerplate but perhaps that'll ease up as well in the future.
