### ISSUE TITLE
Repo locking

### ISSUE THREAD

**Issue by koivunej** [rs-ipfs/rust-ipfs#243]
Not providing any repo locking causes difficult to debug issues as I've hit earlier myself and now others have as well, see #241.

Simplest way could be to fail at [Repo::init](https://github.com/rs-ipfs/rust-ipfs/blob/master/src/repo/mod.rs#L200) time if a lock file exists. If the lock file doesn't exist, one must be created and again removed at exit time. Probably ok to rely on deletion at Drop, require manual recovery (file deletion) unless a (go/js) compatible recovery strategy exists.

While we are not aiming to be 100% repo compatible with the other implementations being compatible here sounds like a solid idea. go-ipfs 0.5 seems to use a simple protocol of creating an empty file `$IPFS_PATH/repo_lock` with the following `/proc/fdinfo/$fd`:

```
$ cat /proc/1159/fdinfo/5
pos:    0
flags:  02100002
mnt_id: 29
lock:   1: POSIX  ADVISORY  WRITE 1159 fd:01:2101410 0 EOF
```

_Originally posted by @koivunej in https://github.com/rs-ipfs/rust-ipfs/issues/241#issuecomment-658802088_

**Comment by aphelionz** [comment]
> Simplest way could be to fail at Repo::init time if a lock file exists. 

FWIW this is what the other implementations do with the `repo.lock` file
