### ISSUE TITLE
use hash_hasher in hashmaps/sets where the key is a Cid/Multihash

### ISSUE THREAD

**Issue by ljedrz** [rs-ipfs/rust-ipfs#258]
Since `Cid`s are already cryptographic-hash-based objects, it makes sense not to do too much extra work hashing them again when used as `HashMap`/`HashSet` keys; the [hash_hasher](https://crates.io/crates/hash_hasher) crate could be used to improve the performance.

**Comment by koivunej** [comment]
`hash_hasher` truncates to least significant (last) 8 bytes: https://docs.rs/hash_hasher/2.0.3/src/hash_hasher/lib.rs.html#87-89

I initially thought using seahash would be fast way to fold the hashes with minimal mixing but can't think of a way this would be worse for cryptographic hashes.

**Comment by ljedrz** [comment]
Isn't it what `SipHasher` (the default `HashMap` hasher) essentially does too? In the end you can only have a `u64` key: https://doc.rust-lang.org/src/core/hash/sip.rs.html#258-295.

**Comment by koivunej** [comment]
> Isn't it what

If by it you mean taking the last 8 bytes of a byte slice, I think SipHasher(s) process all of the input and have a multiround mixing, by the looks of it.

If the comparison was to seahash, both seahash and Siphash seem to process all of the input, but seahash has a simpler mixing, I guess.

I think None of the mixing is needed

**Comment by koivunej** [comment]
Adding the tags, this shouldn't be a too difficult refactoring to try. We do not however have a benchmark which could show that one way is better than the other. Perhaps running manually hyperfine against fetch_and_cat example might work?

Perhaps we should have these in some `ipfs::util` for a while:

 - CidHashSet, MultihashHashSet
 - CidHasMap, MultihashMap

If they seem good, we should propose to move them into cid and multihash crates. Though, might not be a good idea to start doing much work against the bounds with these, just try to use them where we now have `Hash(Set|Map)<\S*Cid`. Hmm, seems that we only have those in the src/repo/mem.rs. Oh, well... It should be enough to see if this would be useful though.
