### ISSUE TITLE
Unixfs adder not found in file (example)

### ISSUE THREAD

**Issue by NukeManDan** [rs-ipfs/rust-ipfs#266]
**Describe the bug**
Trying to use [this example](https://github.com/rs-ipfs/rust-ipfs/blob/master/unixfs/examples/add.rs) fails to `use` the `adder` implemented in `file`

:thinking:  **I suspect this is due to crates.io not having `ipfs-unixfs` updated based on [this refactor](
https://github.com/rs-ipfs/rust-ipfs/commit/f6e78c3ff7db693219a0e22a6289b6c7794970bc) ~ a month ago**

**To Reproduce**
I am building [this demo project](https://gitlab.com/NukeManDan/rust-cid-npm/)based off of the example (100% copy) listed above. It does not build, as it does not find `adder`

**Expected behaviour**
example should compile :pray: 

**Screenshots**
![image](https://user-images.githubusercontent.com/35669742/88594341-409f4f00-d01e-11ea-9420-6de6abb8d5b4.png)

**Comment by koivunej** [comment]
> I suspect this is due to crates.io not having ipfs-unixfs updated based on this refactor ~ a month ago

I think you are correct; the crates.io version hasn't been updated yet. Until it's updated, you should use the ipfs-unixfs like (patch against your demo project Cargo.toml):

```diff
-ipfs-unixfs = "^0.0.1"
+ipfs-unixfs = { git = "https://github.com/rs-ipfs/rust-ipfs" }
```

**Comment by NukeManDan** [comment]
Thanks for the nudge, this got it working! I think it is manually required to update this on crates.io on your end, or whoever has the rights to push new versions.

PS: MVP of the bin is working based on this example for generating a file's CID (v0 and v1) [(here)](https://gitlab.com/NukeManDan/rust-cid-npm/) 

Thanks for making the example easy to extend :rocket:

**Comment by koivunej** [comment]
Ok nice that you got forward! Could you close this, if it's ok, just to make sure we get any following discussion recorded on #247.

**Comment by NukeManDan** [comment]
yes - but should this be closed when crate.io gets a new push for that import?

**Comment by koivunej** [comment]
@NukeManDan: Regarding the next release my thoughts are the following: @c410-f3r has been cooking API ergonomics and has now been looking at no_std. I think we'll cut a 0.1.0 when these are ready, or after we merge the no_std. I've got the tree building parts coming and I am not sure if 0.1.0 should be delayed for *those*, so maybe it's the 0.2.0.
