### ISSUE TITLE
ipfs-http crate has two different runtimes

### ISSUE THREAD

**Issue by c410-f3r** [rs-ipfs/rust-ipfs#275]
Two runtimes: `async-std` from `ipfs` and `tokio` from the crate's internals. This isn't a comfortable situation because of compilation times and additional external dependencies.

If desirable, I am willing to port everything to a single runtime. Just choose the most convenient crate, for example, `tokio` and friends can be replaced with `http-rs` alternatives.

**Comment by koivunej** [comment]
Agreed that the current setup is not ideal, but it has so far been workable. Did you see the hint of [using lld-9](https://github.com/rs-ipfs/rust-ipfs/blob/master/CONTRIBUTING.md#compilation-is-slow-help) in our CONTRIBUTING.md? It of course doesn't save one the compilation time but helps with the huge linker time, at least "on my system".

> If desirable, I am willing to port everything to a single runtime. Just choose the most convenient crate, for example, tokio and friends can be replaced with http-rs alternatives.

`warp` has been so far joy to use so I'd recommend to hold off on any big rewrites for now. Best case scenario would be that the alternatives could use the same "request handler impls" (the non-routing related `async fn`'s, like [`inner_put`](https://github.com/rs-ipfs/rust-ipfs/blob/e224b715ab12bcb942f93aedbe01b1260a2f67bf/http/src/v0/block.rs#L100-L140)). If you already know tide well, could you comment on this?

I've been hoping to have similar alternatives in `ipfs` than the `libp2p` has for using tokio or async-std: https://docs.rs/libp2p/0.22.0/libp2p/tcp/struct.TokioTcpConfig.html, but that of course takes a bit more effort, given the blockstore has to use the same underlying components and we cannot have exclusive features, at least yet. Could be that the implementations just need to be duplicated and use some neat trick to select which one to use if both are enabled. I haven't really looked into this much.

**Comment by c410-f3r** [comment]
@koivunej Thanks for you feedback

More investigation is needed on my side since I am not fully aware about the described nomenclature or the internals machinery. Hope to come up with something feasible in the near future.
