### ISSUE TITLE
Run-time error with bad ipfs path input

### ISSUE THREAD

**Issue by c410-f3r** [rs-ipfs/rust-ipfs#338]
` IpfsPath::from_str("\u{0}\u{1}U\u{0}\u{1}\u{0}/+")` should return `Err` instead of `Ok` and the current behavior makes posterior  operations panic at run-time because of wrong assumptions.

There are likely to be more bad inputs but this particular one threw "thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: MissingProtocolP2p', src/p2p/swarm.rs:227:69"

```rust
use ipfs::{Ipfs, IpfsPath, TestTypes, UninitializedIpfs};
use std::str::FromStr;
use tokio::task;

#[tokio::main]
async fn main() {
    let path = IpfsPath::from_str("\u{0}\u{1}U\u{0}\u{1}\u{0}/+").unwrap();
    let (ipfs, f): (Ipfs<TestTypes>, _) = UninitializedIpfs::default().await.start().await.unwrap();
    task::spawn(f);
    let _ = ipfs.get_dag(path.sub_path("0").unwrap()).await;
}
```

**Comment by ljedrz** [comment]
That panic is mitigated in https://github.com/rs-ipfs/rust-ipfs/pull/335, though we're not yet 100% sure if we should not solve it some other way (the initial assumption that led to the panic makes sense).

**Comment by c410-f3r** [comment]
@ljedrz Thanks

The error won't happen in this scenario with #335 so I am going to close this issue for now
