### ISSUE TITLE
libp2p-rs migration

### ISSUE THREAD

**Issue by kingwel-xie** [rs-ipfs/rust-ipfs#447]
Hi,

We are the owners of [libp2p-rs](https://github.com/netwarps/libp2p-rs), which is an alternative of rust-libp2p. A few days ago, we just released the v0.2.0, which we believe is good enough to start some cool suff with, even it is far away from mature. 

Honestly we don't have much interest on blockchain, on the other side, we think IPFS might be a good point. This is why I'm writing to see if we can work together in a way or as such. Of course we can simply fork from this repo, but before doing that, I really appreciate if someone can explain more about the difference between rust-ipfs and ipfs-rust, in which we can find both have the implementations of ipld/unixfs/bitswap. A bit confusing, to be honest.

Thanks,
Kingwel

**Comment by koivunej** [comment]
Thanks for opening this issue and for letting us know about the alternative libp2p implementation. Right now, our priority right now is to complete the tokio upgrade in #446. From there we'll be moving on to content discovery work, dht publishing, and integrating gossipsub.  Unfortunately, this isn't a priority right now.

If you do end up forking the repo and feel like you've made some gains in benchmarking or performance after a while, please don't hesitate to reach back out!

**Comment by kingwel-xie** [comment]
That's fine, will do. Any heads up about the rust-ipfs and ipfs-rust?

**Comment by koivunej** [comment]
> Any heads up about the rust-ipfs and ipfs-rust?

Both are separate projects with separate goals.

**Comment by kingwel-xie** [comment]
got it. thanx!
