### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by CeryZhai** [rs-ipfs/rust-ipfs#476]
Is the project still alive?

will this project integrate the go-ipfs?

**Comment by koivunej** [comment]
> still alive?

Yes, sort of. We haven't had much time to work on this following other projects. Once I fix my email notifications I should start to react faster to incoming PRs.

> will this project integrate the go-ipfs?

That's not planned. In the meantime you should probably be using go-ipfs directly.
