### ISSUE TITLE
Starting multiple inmemory instanced does not work

### ISSUE THREAD

**Issue by matthiasbeyer** [rs-ipfs/rust-ipfs#481]
**Describe the bug**

In my codebase:

```
---- client::tests::test_post_text_blob stdout ----                                                                   
thread 'client::tests::test_post_text_blob' panicked at 'called `Result::unwrap()` on an `Err` value: The repository is already being used by an IPFS instance.', src/client.rs:130:106                                                     
                                                                                                                      
---- client::tests::test_post_text_chain stdout ----       
thread 'client::tests::test_post_text_chain' panicked at 'called `Result::unwrap()` on an `Err` value: The repository is already being used by an IPFS instance.', src/client.rs:130:106
```

**Expected behavior**

Tests run in parallel

**Additional context**

Running multiple in-memory nodes should be possible, as rust tests run in parallel.

**Comment by matthiasbeyer** [comment]
How would a temporary directory help if everything is in memory anyways?

**Comment by koivunej** [comment]
No, it should not help, nor should it be needed. If this was the case, it'd be a bug. Could you share how are you hitting this issue with in-memory repository? Initialization code, and/or other details would help, or those in comparison to the tests in the repository.

**Comment by matthiasbeyer** [comment]
Yeah, sure: https://git.beyermatthi.as/distrox/tree/src/client.rs?h=ipfs-backend#n127

It is just very simple stuff as I'm still playing with ideas... I am doing nothing more than just `cargo test`, which executes tests in parallel and then causes all tests to fail because the initialization of the ipfs repo fails for all tests.

**Comment by koivunej** [comment]
> `let (ipfs, fut): (ipfs::Ipfs<ipfs::Types>, _) = ...`

Please try replacing `ipfs::Types` with `ipfs::TestTypes`. This is unfortunate fallout from some refactoring which removed the generic type being carried around with `IpfsOptions` without the naming becoming more clear.

**Comment by matthiasbeyer** [comment]
Argh. Thanks!
