### ISSUE TITLE
How to just serve?

### ISSUE THREAD

**Issue by matthiasbeyer** [rs-ipfs/rust-ipfs#484]
Hey,

how to just serve the IPFS repository? Like ... there is no "main loop" thingy documented anywhere AFAICS.

:laughing:

**Comment by koivunej** [comment]
> how to just serve the IPFS repository?

I'm not really sure what you are asking, however the actual p2p capabilities are mostly missing or their integration partially implemented in this implementation even if rust-libp2p would have near complete-ish implementations available.

> there is no "main loop" thingy

This is true. The idea is that `ipfs` would be a library, as such, the user's application would ensure that there is a runtime which lives long enough. You can find an "application example" in under the `http/`, maybe that clears some parts of this up.

**Comment by matthiasbeyer** [comment]
Yeah, I found the `http` example and am currently playing with its ideas... although when my app shuts down I get

```
Error: Invalid argument (os error 22)
```

And I don't know where this is coming from...

**Comment by koivunej** [comment]
> Error: Invalid argument ...

This does not appear to come from within this repository, and it doesn't sound familiar at least. What operating system are you using?

**Comment by matthiasbeyer** [comment]
I'm running on Linux. I also do not get a backtrace with `RUST_BACKTRACE` with this... so I am really confused where this is coming from actually.

**Comment by koivunej** [comment]
Maybe you could find it by removing all other output and [breaking on stdout (or stderr) writes](https://stackoverflow.com/a/1538511).

**Comment by matthiasbeyer** [comment]
Good suggestion, thanks! But it did not work at all.
