### ISSUE TITLE
Requesting to create PR code supporting WordBase-2048 or get feedback on the idea

### ISSUE THREAD

**Issue by will-richards-ii** [rs-ipfs/rust-ipfs#486]
I would like to discuss and solicit me working on a PR to add another base see: https://github.com/multiformats/multibase/issues/89 

**Is your feature request related to a problem? Please describe.**
It's difficult to try to find a way to reference content or smart contracts in paper documents that are used for legal purposes such as recognized DAOs.

**Describe the solution you'd like**
I want to make putting CIDs or other identifiers in legal documents to be easier. Some cannot have barcodes.

**Describe alternatives you've considered**
I thought about typing out the CID but I think lots of errors could occur for someone trying to find it. Some cases won't accept a QR code.

**Comment by koivunej** [comment]
Feel free to follow-up with a PR, though I'm not really sure what does the issue have to do with ipfs library/implementation, sounds like an issue for an application using ipfs.
