### ISSUE TITLE
Relationship of `rust-ipfs` and `ipld-daemon`

### ISSUE THREAD

**Issue by koivunej** [rs-ipfs/rust-ipfs#58]
Or, why not start grant work on top of `ipld-daemon`?

While there is duplicated work in these projects and their subcomponents I feel the ideas presented for `ipld-daemon`, such as, fuse implementation and multi-user support, would work best by having `rust-ipfs` as it's core.

`ipld-daemon` can build around `rust-ipfs` by providing unix domain socket server/client and other operating system specific services like fuse. For `rust-ipfs` and our organization, this work would allow us to eventually *dogfood* or make sure the `rust-ipfs` works as a "library". This would also set an example of one way of handling more experimental and/or platform specific features (such as fuse) outside of `rust-ipfs`.

**Comment by koivunej** [comment]
After editorialization and splitting this from the previous #57 the "experimental" could be defined more unambigiously. In general, I feel that any existing feature feature of `(go|js)-ipfs` which is not on by default or even part of `(go|js)-ipfs` feature set should be considered as "experimental". While work on such features is important to advance the mission of ipfs at large I'd hope such features could be incubated outside of the `rust-ipfs` repository leaving `rust-ipfs` to provide a more "non-experimental" or "stable" user experience once we've finished with the grant work.

**Comment by koivunej** [comment]
A bit late I notice that `rust-ipld` contains parts I remember being in `ipld-daemon` under the crate itself (`rust-ipld/src`). My own understanding of `rust-ipld`'s targets and scope has been limited to what the `rust-ipld/base`, `rust-ipld/dag-cbor` and `rust-ipld/dag-cbor-derive` represent per README description. Since this issue has hopefully already reached interested parties I'm not doing another round of editing but adding this as a comment.

**Comment by dvc94ch** [comment]
yes that's an option. I should probably move the code under src/ to the ipld-daemon. @vmx is planning on implementing selectors, is that going to be a different project alltogether?

The reason why the stuff in src/ is inside the ipld crate is to make ipld-collections reusable. If we move the src/ stuff into ipld-daemon, the ipld-collections crate will only work with the ipld-daemon.

**Comment by koivunej** [comment]
> The reason why the stuff in src/ is inside the ipld crate is to make ipld-collections reusable.

Could you expand on why `rust-ipld` and `ipld-collections` are separate? I understand the concepts to be heavily related. I guess the problem comes from the dependency to the Store traits. Have you ever considered if that could be left out of `rust-ipld` altogether? Making the crates async-less might pave a way towards being able to use in wasm contexts much earlier.. Not that I can immediatedly see a way, since the store is a generic type parameter of a `List<TStore, THash>` for example..

**Comment by dvc94ch** [comment]
So how do you suggest the `List` should interact with the `Store` it needs to query the dag, update the pins to make sure the store doesn't garbage collect them and update the links which represent an ipns entry.

**Comment by vmx** [comment]
> @vmx is planning on implementing selectors, is that going to be a different project alltogether?

Selectors are far down the road. They shouldn't have an impact on immediate decisions.

**Comment by koivunej** [comment]
> So how do you suggest the List should interact with the Store?

My only ideas are to isolate the store access either with a builder which would read out a List cid by cid blockingly. Pinning on mutation would probably need to change happen at "save" time only. Looking at how long my attempts at answering this without code became, I think we can conclude it's at least simpler to write it this way. Perhaps this should be evaluated at length later.

**Comment by dvc94ch** [comment]
> I think we can conclude it's at least simpler to write it this way

I don't follow, which way do you mean?

**Comment by koivunej** [comment]
>> I think we can conclude it's at least simpler to write it this way
> I don't follow, which way do you mean?

Sorry, I meant the `List<TStore, _>` way, as it currently has been implemented.

**Comment by dvc94ch** [comment]
* Pinning on mutation would probably need to change happen at "save" time only

It does happen at save time only, that's what the bufstore is for, to minimize fs accesses in a non mem backed repo. The reason for the many pins/unpins is because the multiuser repo and concurrent garbage collector are largely inspired/being based on the nix daemon as described in eelco dolstras PhD thesis functional package management. Otherwise the collections would only be correct in a single user, single threaded repo with stop the world garbage collection.

**Comment by aphelionz** [comment]
Huh! today I learned about Eelco Dolstras, creator of [Nix and NixOS](https://nixos.org/).

Is this the paper? https://www.usenix.org/legacy/event/hotos07/tech/full_papers/dolstra/dolstra.pdf

**Comment by dvc94ch** [comment]
That's a start, but the only source describing the extensional/intensional store models and the garbage collection algorithms is https://nixos.org/~eelco/pubs/phd-thesis.pdf For a build farm concurrent garbage collection is important as the disk fills up quickly and there's never a time to stop and garbage collect.
