### ISSUE TITLE
Fix dnslink lookup

### ISSUE THREAD

**Issue by dvc94ch** [rs-ipfs/rust-ipfs#83]
Previously `domain` was used but that is tokio-0.1 library. Now `domain` seems to have upgraded to latest tokio in https://github.com/NLnetLabs/domain.

Our needs for the DNS are:
 * stub resolving
 * TXT records to get dnslink [1](https://docs.ipfs.io/concepts/dnslink/#resolve-using-dnslink) [2](https://dnslink.io/)

rust-libp2p should already handle resolving names in `/dns4` and `/dns6` multiaddrs through threadpooled (stub?) resolver (haven't checked which library).

Being able to resolve dnslinks is the desired outcome. The async-std dependency seems a bit difficult. Alternatives on tokio would include trust-dns. Even if we decide to add back tokio support, we should be considering the what ever way libp2p is using as something we could leave for async-std.

**Comment by koivunej** [comment]
I think this is now fixed with some of lukasz latest dep update PRs.

**Comment by ljedrz** [comment]
Ah yeah, the related tests pass (when enabled with `tokio`) after https://github.com/rs-ipfs/rust-ipfs/pull/290/commits/cb0fa7b3a4734d7bc379a225d548f2c80464d934.

**Comment by koivunej** [comment]
And now we are fully tokio so this is always enabled.
